src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IdNegozio__c</fullName>
        <label>IdNegozio</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_Case__c</fullName>
        <formula>Hyperlink(&quot;https://unieuro--dev1.cs83.my.salesforce.com/&quot; &amp;Id , &quot;Dettaglio&quot;)</formula>
        <label>Numero Case</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SG_Force_Test_Controller.cls
public class SG_Force_Test_Controller {

	public string idNegozio {get; set;}

	public List<Case> listacasi{get; Set;}

	public SG_Force_Test_Controller(ApexPages.StandardController stc){
	idNegozio = ApexPages.currentPage().getParameters().get('idNegozio');
	System.debug(idNegozio);
	listacasi= [select Id, CaseNumber, Subject, Status, CreatedDate, OwnerId, Numero_Case__c, IdNegozio__c from Case where IdNegozio__c=:idNegozio];
	}
}