src/objects/Config_cs_casePicklistValues__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical custom setting that provides access to some case field picklist values based on user profiles. 
The label of each custom setting field is the same as the label of the case field it represents.</description>
    <fields>
        <fullName>TestPicklist_cs__c</fullName>
        <description>Custom setting field representing the picklist values available to the case TestPicklist__c field.</description>
        <label>TestPicklist</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Case Picklist Values</label>
</CustomObject>

src/classes/SG_retrVisibility_AND_PicklistValuesTest.cls
// 11/2016 Matteo Facchini

@isTest
private class SG_retrVisibility_AND_PicklistValuesTest {

static private void InsertCustomSettings(){
    // Instantiating Custom setting for the system administrator profile
    Config_cs_casePicklistValues__c cs = new Config_cs_casePicklistValues__c();
    cs.SetupOwnerId = userInfo.getProfileId();
    cs.TestPicklist_cs__c = '';
    insert cs;

    Config_cs_casePicklistValues__c csOrg = new Config_cs_casePicklistValues__c();
    csOrg.SetupOwnerId = userInfo.getOrganizationId();
    csOrg.TestPicklist_cs__c = 'A,B,C,D,E,F';
    insert csOrg;
}

 static testmethod void Test_getTestPicklist_SystemAdmin(){
    InsertCustomSettings();

    // Instantiating the controller
    SG_retrieveVisibility_AND_PicklistValues c = new SG_retrieveVisibility_AND_PicklistValues();
    c.m_sobject = (SObject) new Case();

    //c.getTestPicklist();

    //System.assertEquals('System Administrator', c.profileName);

 }

 static testmethod void Test_getTestPicklist_StandardUser(){
    InsertCustomSettings();

    // Instantiating the controller
    SG_retrieveVisibility_AND_PicklistValues c = new SG_retrieveVisibility_AND_PicklistValues();
    
    //c.getTestPicklist();

    //System.assertEquals('Standard User', c.profileName);

 }
}