src/objects/Log_Errori__c.object
<CustomObject>
    <description>Oggetto utilizzato per scrivere gli errori restituiti dai Web service</description>
    <fields>
        <fullName>Codice_errore__c</fullName>
        <label>Codice errore</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Descrizione__c</fullName>
        <label>Descrizione</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Loyalty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loyalty</label>
        <referenceTo>Loyalty__c</referenceTo>
        <relationshipLabel>Log Errori</relationshipLabel>
        <relationshipName>Log_Errori</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Richiesta_Voucher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Richiesta Voucher</label>
        <referenceTo>Richiesta_Voucher__c</referenceTo>
        <relationshipLabel>Log Errori</relationshipLabel>
        <relationshipName>Log_Errori</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Log Errori</label>
    <nameField>
        <displayFormat>E-{000000000}</displayFormat>
        <label>Numero Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Errori</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Loyalty__c.object
<CustomObject>
    <description>Anagrafiche delle loyalty</description>
    <label>Loyalty</label>
    <nameField>
        <label>Codice carta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Richiesta_Voucher__c.object
<CustomObject>
    <description>Oggetto utilizzato per la richiesta dei Voucher ad Hybris</description>
    <fields>
        <fullName>Descrizione__c</fullName>
        <label>Descrizione</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Richiesta Voucher</label>
    <nameField>
        <displayFormat>RV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Richieste Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SG_UNIEURO_Utility_Test.cls
@isTest
private class SG_UNIEURO_Utility_Test {

	@isTest
	private static void testWriteErrorLog1() {
		Loyalty__c l = SG_Test_Utility.insertNewLoyalty();
		
		String code = '123456';
		String descr = 'TEST-DESCR';
		SG_UNIEURO_Utility.WriteErrorLog(l.id, code, descr);
		
		// verifico che l'elemento sia stato creato come deve
		List<Log_Errori__c> lerr = [select id, Loyalty__c, Codice_errore__c, Descrizione__c from Log_Errori__c];
		system.assertEquals(1, lerr.size());
		system.assertEquals(code, lerr[0].Codice_errore__c);
		system.assertEquals(descr, lerr[0].Descrizione__c);
		system.assertEquals(l.id, lerr[0].Loyalty__c);
	}

	@isTest
	private static void testWriteErrorLog2() {
		Richiesta_Voucher__c r = SG_Test_Utility.insertNewRichiestaVoucher();
		
		String code = '123456';
		String descr = 'TEST-DESCR';
		SG_UNIEURO_Utility.WriteErrorLog(r.id, code, descr);
		
		// verifico che l'elemento sia stato creato come deve
		List<Log_Errori__c> lerr = [select id, Richiesta_Voucher__c, Codice_errore__c, Descrizione__c from Log_Errori__c];
		system.assertEquals(1, lerr.size());
		system.assertEquals(code, lerr[0].Codice_errore__c);
		system.assertEquals(descr, lerr[0].Descrizione__c);
		system.assertEquals(r.id, lerr[0].Richiesta_Voucher__c);
	}

	@isTest
	private static void testfindObjectNameFromRecordIdPrefix(){
		Loyalty__c l = SG_Test_Utility.insertNewLoyalty();
	
		String sobjName = SG_UNIEURO_Utility.findObjectNameFromRecordIdPrefix(l.id);

		// verifico che dall'id del record fornito, la funzione recuperi correttamente l'API name dell'oggetto
		system.assertEquals(Schema.SOBjectType.Loyalty__c.name, sobjName);
	}
}