src/objects/Loyalty__c.object
<CustomObject>
    <description>Anagrafiche delle loyalty</description>
    <fields>
        <fullName>Data_Inizio__c</fullName>
        <label>Data Inizio</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Scadenza__c</fullName>
        <label>Data Scadenza</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Motivo_Inattivita_Carta__c</fullName>
        <label>Motivo Inattivita Carta</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Loyalty</label>
    <nameField>
        <label>Codice carta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Richiesta_Voucher__c.object
<CustomObject>
    <description>Oggetto utilizzato per la richiesta dei Voucher ad Hybris</description>
    <fields>
        <fullName>Codice_promozione__c</fullName>
        <label>Codice promozione</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Testo_promozione__c</fullName>
        <label>Testo promozione</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Richiesta Voucher</label>
    <nameField>
        <displayFormat>RV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Richieste Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SG_Test_Utility.cls
public class SG_Test_Utility {

	public static Loyalty__c insertNewLoyalty(){
		Loyalty__c l = new Loyalty__c();
		l.name = 'TEST-LOYALTY-' + String.valueOf((Integer) Math.random()*10000);
		l.Data_Inizio__c = Date.today();
		l.Data_Scadenza__c = l.Data_Inizio__c.addDays((Integer) Math.random()*100);
		l.Motivo_Inattivita_carta__c = 'TEST MOTIVO INATTIVITa CARTA';
		insert l;
		return l;
	}

	public static Richiesta_Voucher__c insertNewRichiestaVoucher(){
		Richiesta_Voucher__c r = new Richiesta_Voucher__c();
		
		r.Testo_promozione__c = 'TEST-VOUCHER-' + String.valueOf((Integer) Math.random()*10000);
		r.Codice_promozione__c = 'ABC';
	
		insert r;
		return r;
	}

}