src/objects/Restrizioni_Voucher__c.object
<CustomObject>
    <description>Restrizioni applicabili alla richiesta di voucher verso Hybris</description>
    <fields>
        <fullName>Richiesta_Voucher__c</fullName>
        <label>Richiesta Voucher</label>
        <referenceTo>Richiesta_Voucher__c</referenceTo>
        <relationshipLabel>Restrizioni Vouchers</relationshipLabel>
        <relationshipName>Restrizioni_Vouchers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Restrizione Voucher</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Restrizioni Vouchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Richiesta_Voucher__c.object
<CustomObject>
    <description>Oggetto utilizzato per la richiesta dei Voucher ad Hybris</description>
    <fields>
        <fullName>Restrizioni__c</fullName>
        <description>00 Nessuna restrizione
10 Restrizione per numero di Ordini (per clienti regolari)
20 Restrizione per revenue (per clienti regolari)
30 Restrizione per nuovi clienti
40 Restrizione per valore dell&apos;ordine
50 Restrizione per prodotto
60 Restrizione per categoria prodotto
70 Restrizione per quantità ordinata
80 Restrizione per utente
90 Restrizione temporanea</description>
        <inlineHelpText>Scegliere quali restrizioni applicare alla richiesta dei voucher</inlineHelpText>
        <label>Restrizioni</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <default>true</default>
                    <label>00</label>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>70</fullName>
                </value>
                <value>
                    <fullName>80</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stato__c</fullName>
        <description>N - nuovo
I - In eleaborazione
C - Chiuso
E - Errore</description>
        <label>Stato</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Richiesta Voucher</label>
    <nameField>
        <displayFormat>RV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Richieste Vouchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SG_richiestaVoucherTrigger_UtilityClass.cls
// MSozzi 23/03/2017 utility class contenente metodi statici per i trigger sull'oggetto richiesta_voucher__c
public class SG_richiestaVoucherTrigger_UtilityClass {

	// creazione record Restrizioni_Voucher__c sulla base dei valori di picklist Restrizioni__c
	public static void insertRestrizioniVoucher(Map<Id, Richiesta_Voucher__c> mapRichieste){
		List<Restrizioni_Voucher__c> restrVoucher = new List<Restrizioni_Voucher__c>();

		for(Richiesta_Voucher__c rv : mapRichieste.values()){

			if((rv.stato__c == SG_UNIEURO_Utility.PICKVAL_NEW) || 
			   (rv.stato__c == SG_UNIEURO_Utility.PICKVAL_INPROGRESS) || 
			   (rv.stato__c == SG_UNIEURO_Utility.PICKVAL_ERROR))
			{
				// recupero lista valori selezionati
				Set<String> userSelectedValues = new Set<String>();
				userSelectedValues.addAll(rv.Restrizioni__c.split(';'));

				// tengo solo i numerelli
				Set<String> userSelectedValues_Numbers = new Set<String>();
				for(String s : userSelectedValues){
					userSelectedValues_Numbers.add(s.replaceAll('[A-Za-z]',''));
				}

				// estraggo tutti i record type per Restrizioni_Voucher__c
				List<RecordType> restrVoucher_RT = [select id, name from RecordType where SObjectType = 'Restrizioni_Voucher__c'];

				// metto i record type in una mappa ordinata per numerello
				Map<String, RecordType> Map_restrVoucher_RT = new Map<String, RecordType>();
				for(RecordType rt : restrVoucher_RT)
					Map_restrVoucher_RT.put(rt.name.replaceAll('[A-Za-z]',''), rt);

				for(String snum : userSelectedValues_Numbers){
					if(Map_restrVoucher_RT.containsKey(snum)){
						Restrizioni_Voucher__c restrV = new Restrizioni_Voucher__c();
						restrV.Richiesta_Voucher__c = rv.id;
						restrV.recordType = Map_restrVoucher_RT.get(snum);

						restrVoucher.add(restrV);
					}
				}

			}	// Fine if sullo stato di Richiesta_Voucher__c

		} // Fine loop su Richiesta_Voucher__c
	
		upsert restrVoucher;
	}


}