src/objects/SG_Endpoint_Web_Service__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Gestione degli indirizzi utilizzati nei web service</description>
    <fields>
        <fullName>Aggiornamento_ordine__c</fullName>
        <description>aggiornamento ordini su Hybris (caso di ordini annullati)</description>
        <inlineHelpText>aggiornamento ordini su Hybris (caso di ordini annullati)</inlineHelpText>
        <label>Aggiornamento ordine</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Richiesta_ultimi_ordini__c</fullName>
        <description>richiesta degli ultimi ordini web ad Hybris</description>
        <inlineHelpText>richiesta degli ultimi ordini web ad Hybris</inlineHelpText>
        <label>Richiesta ultimi ordini</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Endpoint Web Service</label>
</CustomObject>

src/classes/SG_WS_Ordini.cls
global class SG_WS_Ordini { 

	webservice static string RichiestaOrdini (string CodCliente){ //metodo per richiedere gli ultimi ordini web ad Hybris
		string risultato='';
		Http http = new Http();
		HttpRequest request = new HttpRequest();
		SG_Endpoint_Web_Service__c mc = SG_Endpoint_Web_Service__c.getOrgDefaults();
		mc.Richiesta_ultimi_ordini__c='';
		request.setEndpoint('mc.Richiesta_ultimi_ordini__c');
		request.setMethod('GET');
		HttpResponse response = http.send(request);
		 if (response.getStatusCode() == 200) {
			Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
			List<Object> ordini = (List<Object>) results.get('ordini');
			System.debug('Received the following orders:');
            for (Object esempio : ordini) {
                System.debug(ordini);
			}	
			risultato='OK';
			}
		else
			risultato='KO';

		return risultato;
	}

	webservice static string AggiornamentoOrdini (string CodCliente){ //metodo per aggiornare gli ordini web ad Hybris
		string risultato='';
		Http http = new Http();
		HttpRequest request = new HttpRequest();
		SG_Endpoint_Web_Service__c mc = SG_Endpoint_Web_Service__c.getOrgDefaults();
		mc.Aggiornamento_ordine__c='';
		request.setEndpoint('mc.Aggiornamento_ordine__c');
		request.setMethod('GET');
		HttpResponse response = http.send(request);
		 if (response.getStatusCode() == 200) {
			Map<String, Object> results = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
			List<Object> ordini = (List<Object>) results.get('ordini');
			System.debug('Received the following orders:');
            for (Object Order : ordini) {
                System.debug(ordini);
			}	
			risultato='OK';
		}
		else
			risultato='KO';	
		return risultato;
	}

}